### ISSUE TITLE
Bot的CrownX,Y坐标获取异常导致读取undefined从而引发崩溃

### ISSUE THREAD

**Issue by Bai-Tian** [By-Ha/Checkmate#1]

**Comment by By-Ha** [comment]
我这并没有守护所以只要出问题就会崩,加上我的码力实在太差了,我现在看看

**Comment by By-Ha** [comment]
bot的问题,,,,我去把bot禁用了,本来这个bot也是垃圾bot(手动笑哭

**Comment by By-Ha** [comment]
现在测试服务器把bot禁用了,最近期中考试有点忙,等我考完了再修

**Comment by Bai-Tian** [comment]
谢谢回复~ 加油鸭，我也期中考了（

**Comment by Bai-Tian** [comment]
昨天去除掉机器人之后，和朋友两个人连接到服务器之后就崩溃了。今天服务器恢复之后 ，刚才用电脑和手机测试了一下两个人登陆，正常的玩了一局，于是要准备开第二局然后就崩溃了。。（我错了 不要打我www）

**Comment by By-Ha** [comment]
我好难,因为之前加了机器人,允许了一个人加入,然后,把机器人禁用了,,,,理论上不能一个人,但是没有判断,进去后不能找到一个人的地图,然后崩了

**Comment by By-Ha** [comment]
看来找个时间还要把守护写了,现在好了,不过现在没有机器人

**Comment by By-Ha** [comment]
重启了,现在应该是稳定的(至少我希望

**Comment by Bai-Tian** [comment]
刚才和朋友玩了几局，发现了如下问题：
2个人开始游戏的时候有的地图太小了
2个人开始游戏的时候有的地图太小了，并且两方的王都可能在半径3格内，太近了
好像只能2个人玩，服务器最高有四个人在线，有的时候大家都点准备了，但是每次只有两个人的游戏开始。准备之后如果游戏开始了，没被选中的玩家会懵逼（不知道是进入游戏了还是开始游戏了没带我）
如果不想修或者没时间的话就不用修了w 考试要紧 辛苦了~ww

**Comment by By-Ha** [comment]
23333,你可以提pr😂

**Comment by Bai-Tian** [comment]
本鶸还不会写js..qwq 就不指指点点了（逃）

**Comment by By-Ha** [comment]
其实不难,对着改就行了,这个repo本来就是我学nodejs用的😀

**Comment by By-Ha** [comment]
更新了3.0,并且表示再也不想碰bot了😂
